from platform1 import logger

logger.reset_log_file()

logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
logger.log("test", "ip")
